### ISSUE TITLE
Error parsing expressions with unary minus ("-a") and unary plus ("+a")

### ISSUE THREAD

**Issue by nfsantos** [raw-db/raw#51]
Error with unary minus -a, -(-a)

```
Parser error: [1.2] failure: string matching regex `-?(\d+(\.\d*)?|\d*\.\d+)([eE][+-]?\d+)?[fFdD]?' expected but `a' found

-a
 ^

an implementation is missing
scala.NotImplementedError: an implementation is missing
	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:225)
	at raw.calculus.FunTest.parse(FunTest.scala:13)
	at raw.calculus.SyntaxAnalyzerTest.isOK(SyntaxAnalyzerTest.scala:16)
    ...
```

Error with unary plus:
```
Parser error: [1.1] failure: `not' expected but `+' found

+a
^

an implementation is missing
scala.NotImplementedError: an implementation is missing
	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:225)
	at raw.calculus.FunTest.parse(FunTest.scala:13)
	at raw.calculus.SyntaxAnalyzerTest.isOK(SyntaxAnalyzerTest.scala:16)
    ...
```

**Comment by miguel-branco** [comment]
This issue was moved to raw-labs/raw#29
