### ISSUE TITLE
Unnester fails with expressions with empty qualifier

### ISSUE THREAD

**Issue by nfsantos** [raw-db/raw#53]
Example query:
`for (a <- set(3)) yield set 1`

Output:
```
17:11:08.517 [ScalaTest-run-running-MyTest] DEBUG raw.calculus.Uniquifier$ - Uniquifier input tree: for (a <- { 3 }) yield set 1
17:11:08.544 [ScalaTest-run-running-MyTest] DEBUG raw.calculus.Uniquifier$ - Uniquifier output tree: for ($1 <- { 3 }) yield set 1
17:11:08.545 [ScalaTest-run-running-MyTest] DEBUG raw.calculus.Normalizer$ - Normalizer input tree: for (a <- { 3 }) yield set 1
17:11:08.561 [ScalaTest-run-running-MyTest] DEBUG raw.calculus.Normalizer$ - Applying normalizer rule 6
17:11:08.562 [ScalaTest-run-running-MyTest] DEBUG raw.calculus.Normalizer$ - Applying normalizer rule 1
17:11:08.571 [ScalaTest-run-running-MyTest] DEBUG raw.calculus.Normalizer$ - Normalizer output tree: for () yield set 1
17:11:08.572 [ScalaTest-run-running-MyTest] DEBUG raw.calculus.Simplifier$ - Simplifier input tree: for () yield set 1
17:11:08.596 [ScalaTest-run-running-MyTest] DEBUG raw.calculus.Simplifier$ - Simplifier output tree: for () yield set 1
17:11:08.596 [ScalaTest-run-running-MyTest] DEBUG raw.algebra.Unnester$ - Unnester input tree: for () yield set 1

raw.algebra.UnnesterError was thrown.
Invalid output expression: Some(CalculusTerm(Comp(SetMonoid(),List(),IntConst(1)),List(),List(),EmptyTerm))
	at raw.algebra.Unnester$.raw$algebra$Unnester$$unnest$1(Unnester.scala:34)
	at raw.algebra.Unnester$.apply(Unnester.scala:269)
	at raw.Query$.unnest(Query.scala:38)
	at raw.Query$.apply(Query.scala:43)
```

**Comment by miguel-branco** [comment]
Related to #17, but needs an additional simplification rule (which I believe should be there already... :S to turn `for () yield set 1` to zero monoid of set.

**Comment by miguel-branco** [comment]
This issue was moved to raw-labs/raw#27
